### ISSUE TITLE
File streams interrupted. 

### ISSUE THREAD

**Issue by BernardGoldberger** [icing/mod_h2#120]
Hi,

I'm not sure if the is the right place to report this, but I'm kind of going in circles.

[Here](https://github.com/phanan/koel/issues/448) https://github.com/phanan/koel/issues/448 is a detailed report of the issue and my findings so far.

**Comment by YakovGoldberger** [comment]
Version 1.8.7

> fix for h2 session ignoring new responses while already open streams continue to have data available.

Is it meant to fix this issue?

**Comment by icing** [comment]
No, since I did not get any ingormation on how to reproduce. it might affect this. can you test?

**Comment by YakovGoldberger** [comment]
Once the Win versions are released I'll test and report back.

**Comment by icing** [comment]
@YakovGoldberger do you still have this issue with the current release? If not, just report so I can close this issue with good conscience. :-)

**Comment by YakovGoldberger** [comment]
@icing is there a win release for this version available? the last version I tested was 1.10.3

**Comment by icing** [comment]
Not a windows user myself, but maybe at [apachelounge](https://www.apachelounge.com/download/)?

**Comment by YakovGoldberger** [comment]
I checked and there wasn't, I'll request it in the forum.

**Comment by Jan-E** [comment]
Which version? VC9, VC11, VC14 or VC15? x86 or x64?

**Comment by Jan-E** [comment]
@YakovGoldberger Guessing from your headers, try the mod_http2.so in
https://phpdev.toolsforresearch.com/openssl-1.0.2l-fips-2.4.27-x64-vc14.zip

**Comment by SteffenAL** [comment]
On Apachelounge  available:  the latest mod_http2 1.10.10 VC15 based on 2.4.27

https://www.apachelounge.com/viewtopic.php?p=35652

**Comment by Jan-E** [comment]
@SteffenAL You did not include nghttp2.dll in the download. For people that upgrade from v1.8.7 it might be necessary to upgrade the nghttp2.dll as well. My download has nghttp2 built statically into mod_http2.so, it does not need a separate dll.

**Comment by YakovGoldberger** [comment]
Thank you both, I just upgraded from 2.4.25 to 27 I have to finish configuring everything and I will give it a try.

**Comment by SteffenAL** [comment]
@Jan-E Based on 2.4.27, nghttp2.dll is still the same as in 2.4.27.

**Comment by Jan-E** [comment]
Yeah, but Yakov _was_ on 2.4.25.

**Comment by icing** [comment]
Thanks.

**Comment by YakovGoldberger** [comment]
Ooops, didn't mean to close, will test and reopen if it's still an issue.

**Comment by YakovGoldberger** [comment]
Just tested and the issue is still ongoing.

**Comment by YakovGoldberger** [comment]
```
t=191394 [st=1241]  HTTP2_STREAM_UPDATE_RECV_WINDOW
                    --> delta = 1221
                    --> window_size = 15720457
t=191394 [st=1241]  HTTP2_STREAM_UPDATE_RECV_WINDOW
                    --> delta = 8183
                    --> window_size = 15728640
t=191396 [st=1243]  HTTP2_SESSION_RECV_RST_STREAM
                    --> error_code = "8 (CANCEL)"
                    --> stream_id = 1
t=197398 [st=7245]  HTTP2_SESSION_RECV_GOAWAY
                    --> active_streams = 0
                    --> debug_data = "timeout"
                    --> error_code = "0 (NO_ERROR)"
                    --> last_accepted_stream_id = 1
                    --> unclaimed_streams = 0
t=197398 [st=7245]  HTTP2_SESSION_CLOSE
                    --> description = "Finished going away"
                    --> net_error = 0 (?)
t=197398 [st=7245]  HTTP2_SESSION_POOL_REMOVE_SESSION
                    --> source_dependency = 245845 (HTTP2_SESSION)
t=197398 [st=7245] -HTTP2_SESSION
```

**Comment by YakovGoldberger** [comment]
@icing I do want to point out again that it's not an issue in Firefox. [I mentioned it in the original post [koel issue 448](https://github.com/phanan/koel/issues/448)]

**Comment by icing** [comment]
@YakovGoldberger Ah, now I understand the issue. The request is victim to the mod_h2 DoS protection. The protection basically looks for clients that use HTTP/2 flow control to block server threads into doing basically nothing.

Which is what the audio player does, but with good intentions. If the audio streamed would come out of a static file, this would not trigger. But as I read it, there is an active PHP request going on the whole time.

As koel seems to be targeted for in-house use, DoS protection is probably not an issue. Unless you have friends who want to annoy you.

Let me think about this a bit. Maybe there is a good approach that works in all setups without the user needing to configure special things.

**Comment by icing** [comment]
@YakovGoldberger could you give v1.10.11 a try? Thanks!

**Comment by YakovGoldberger** [comment]
@icing is there a win version available?

**Comment by icing** [comment]
@SteffenAL can you make a win build for it when you find the time? Thanks!

**Comment by SteffenAL** [comment]
Done, see https://www.apachelounge.com/viewtopic.php?p=35806

**Comment by icing** [comment]
Thanks!

**Comment by YakovGoldberger** [comment]
@SteffenAL thank you.

@icing just tested it and the stream still gets closed, I attached the h2 data output
[koel h2 error 2.txt](https://github.com/icing/mod_h2/files/1284609/koel.h2.error.2.txt)
[koel h2 error 1.txt](https://github.com/icing/mod_h2/files/1284610/koel.h2.error.1.txt)

```
[Thu Sep 07 08:06:49.682052 2017] [http2:info] [pid 13672:tid 464] AH03090: mod_http2 (v1.10.11-git, feats=, nghttp2 1.25.0), initializing...
[Thu Sep 07 08:06:49.682052 2017] [http2:trace1] [pid 13672:tid 464] h2_h2.c(447): h2_h2, child_init
[Thu Sep 07 08:06:49.682052 2017] [http2:trace1] [pid 13672:tid 464] h2_switch.c(43): h2_switch init
[Thu Sep 07 08:06:49.957068 2017] [mpm_winnt:notice] [pid 13672:tid 464] AH00455: Apache/2.4.27 (Win64) OpenSSL/1.1.0f mod_watch/4.3P PHP/7.1.4 configured -- 
```
